config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:registrations => "user/registrations"}
  resources :products do
    resources :reviews
  end
  resource :home, :index

  resources :charges, :only => [:new, :create]

  resources :order_items

  resources :addresses, :only => [:create]

  resource :cart, only: [:show]

  root :to => "products#home"

  get "cart/selectaddress", to: "carts#selectaddress"
  post "cart/processaddress", to: "carts#processaddress"


  get "*path", to: redirect('/')
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items.most_recent

  end

  def selectaddress
    if user = current_user
      user_account = user.account
      @current_order = current_order
      @user_addresses = user_account.addresses if user_account.addresses.any?
    end
    @address = Address.new
  end

  def processaddress
    current_order.update(:address_id => params[:address_id])
    redirect_to new_charge_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_checkout_form.html.erb
<% if @user_addresses %>
	<%= form_tag cart_processaddress_path do |f| %>
	<div class="form-check">
			<% @user_addresses.each do |address| %>
			<div class="form-check">
				<label class="form-check-label">
					<%= radio_button_tag :address_id, address.id, class: "form-check-input" %>
					<%= "#{address.full_name} #{address.street1} #{address.street2} #{address.city}, #{address.state} #{address.zipcode}" %>
				</label>
			</div>
			<% end %>
			<%= submit_tag "Continue", :class => "btn btn-success" %>
		</div>
	<% end %>
<% else %>
	<%= form_for @address do |f| %>
		<div class="form-group"> <!-- Full Name -->
	    <%= f.label :full_name %><br />
	    <%= f.text_field :full_name, autofocus: true, :class => "form-control", :placeholder => "Bob Markman" %>
		</div>

		<div class="form-group"> <!-- Street 1 -->
	    <%= f.label :street1 %><br />
	    <%= f.text_field :street1, :class => "form-control", :placeholder => "1234 N Main St." %>
		</div>

		<div class="form-group"> <!-- Street 2 -->
	    <%= f.label :street2 %><br />
	    <%= f.text_field :street2, :class => "form-control", :placeholder => "Unit 1 (Optional)" %>

		<div class="form-group"> <!-- City-->
	    <%= f.label :city %><br />
	    <%= f.text_field :city, :class => "form-control", :placeholder => "Portland" %>
		</div>

		<div class="form-group"> <!-- State -->
			<%= f.label :state%><br />
	    <%= f.select :state,
						[["Alabama","AL"],
						["Alaska","AK"],
						["Arizona","AZ"],
						["Arkansas","AR"],
						["California","CA"],
						["Colorado","CO"],
						["Connecticut","CT"],
						["Delaware","DE"],
						["District Of Columbia","DC"],
						["Florida","FL"],
						["Georgia","GA"],
						["Hawaii","HI"],
						["Idaho","ID"],
						["Illinois","IL"],
						["Indiana","IN"],
						["Iowa","IA"],
						["Kansas","KS"],
						["Kentucky","KY"],
						["Louisiana","LA"],
						["Maine","ME"],
						["Maryland","MD"],
						["Massachusetts","MA"],
						["Michigan","MI"],
						["Minnesota","MN"],
						["Mississippi","MS"],
						["Missouri","MO"],
						["Montana","MT"],
						["Nebraska","NE"],
						["Nevada","NV"],
						["New Hampshire","NH"],
						["New Jersey","NJ"],
						["New Mexico","NM"],
						["New York","NY"],
						["North Carolina","NC"],
						["North Dakota","ND"],
						["Ohio","OH"],
						["Oklahoma","OK"],
						["Oregon","OR"],
						["Pennsylvania","PA"],
						["Rhode Island","RI"],
						["South Carolina","SC"],
						["South Dakota","SD"],
						["Tennessee","TN"],
						["Texas","TX"],
						["Utah","UT"],
						["Vermont","VT"],
						["Virginia","VA"],
						["Washington","WA"],
						["West Virginia","WV"],
						["Wisconsin","WI"],
						["Wyoming","WY",]
					]
			%>
		</div>

		<div class="form-group"> <!-- ZipCode-->
			<%= f.label :zipcode %><br />
			<%= f.text_field :zipcode, :class => "form-control", :placeholder => "97214" %>
		</div>

		<div class="form-group"> <!-- Submit Button -->
			<%= f.submit "Continue!", class: "btn btn-success" %>
		</div>
	<% end %>
<% end %>

app/views/carts/_form.html.erb
<%= form_for(item, remote: true) do |f|%>
  <%= f.number_field :quantity, min: 1, max: 100, step: 1 %>
  <%= f.submit "Update Quantity" %>
<% end %>

app/views/carts/_order_item.html.erb
<%= image_tag(item.product.photo.url(:thumb)) %>
<p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete", remote: true} %></p>
<!-- Shorthand: item: item ===> in partial 'item' -->
<%= render "carts/form", :item => item  %>
<p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>

app/views/carts/checkout.html.erb
<% if @address %>
  <%= render "layouts/errors", :object => @address %>
<% end %>

<div class="row justify-content-center mt-4">
  <div class="col-9">
    <div class="card card-body">
      <h1 class="text-center">Checkout</h1>
      <%= render 'carts/checkout_form' %>
    </div>
  </div>
</div>

app/views/carts/destroy.js.erb
$('#order_item_<%=@item.id%>').remove();
$('#total-price').html('<%= number_to_currency @total %>');
$('#items-in-cart').html('<%= items_in_cart %>');

app/views/carts/selectaddress.html.erb
<% if @address %>
  <%= render "layouts/errors", :object => @address %>
<% end %>

<div class="row justify-content-center mt-4">
  <div class="col-9">
    <div class="card card-body">
      <h1 class="text-center">Select Address</h1>
      <%= render 'carts/checkout_form' %>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
<% if @order_items.any? %>
  <% @order_items.each do |item| %>
  <div id="order_item_<%= item.id %>"><%= render 'order_item', :item => item %></div>
  <% end %>
  <p>Your Total: <span id='total-price'><%= number_to_currency current_order.total_price %></span></p>
  <%= link_to "Checkout", cart_selectaddress_path, :class => "btn btn-primary"%>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>

app/views/carts/update.js.erb
$('#order_item_<%=@item.id%>').html("<%= j render 'carts/order_item', :item => @item %>");
$('#total-price').html('<%= number_to_currency @total %>');
$('#items-in-cart').html('<%= items_in_cart %>');