config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:registrations => "user/registrations"}
  resources :products do
    resources :reviews
  end
  resource :home, :index

  resources :charges, :only => [:new, :create]

  resources :order_items

  resources :addresses, :only => [:create]

  resource :cart, only: [:show]

  root :to => "products#home"

  get "cart/selectaddress", to: "carts#selectaddress"
  post "cart/processaddress", to: "carts#processaddress"


  get "*path", to: redirect('/')
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
  has_many :reviews

  validates :name, presence: true
  validates :price, presence: true, numericality: { only_decimal: true, greater_than: 0 }

  has_attached_file :photo, :styles => { :large => "600x600", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  scope :honey, -> { where(category: "honey")}
  scope :equipment, -> { where(category: "equipment")}
  scope :hive, -> { where(category: "hive")}
  scope :bee, -> { where(category: "bee")}
  scope :bee_product, -> { where(category: "bee_product")}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @products = Product.honey if params[:category] === "honey"
    @products = Product.bee if params[:category] === "bee"
    @products = Product.hive if params[:category] === "hive"
    @products = Product.equipment if params[:category] === "equipment"
    @products = Product.bee_product if params[:category] === "bee_product"
    @reviews = Review.group('product_id').average('rating')
  end

  def show
    @product = Product.find(params[:id])
    @order_item = current_order.order_items.new
    @reviews = @product.reviews
  end

  def home

  end



  private

  def item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @order_item do |f| %>
  <%= f.hidden_field :product_id, value: @product.id %>
  <%= f.select :quantity, 1..20 %>
  <%= f.submit "Add to cart" %>
<% end %>

app/views/products/_product.html.erb
<div class="card mt-2 mb-2">

  <%= image_tag(product.photo.url(:medium), class: "card-img-top") %>

  <div class="card-body">
    <h4 class="card-title"><%= product.name %></h4>
    <% if @reviews[product.id] %>
      <p>Average Review: <%= @reviews[product.id].round(2)%></p>
    <% elsif %>
      <p>No Reviews Yet</p>
    <% end %>
    <p class="card-text"><%= number_to_currency product.price %></p>
  </div>
</div>

app/views/products/home.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <a href="/products/?category=honey">
      <%= image_tag('honey2.jpg', class: "d-block img-fluid") %>
      </a>
      <div class="carousel-caption d-none d-md-block">
        <h3>Honey</h3>
      </div>
    </div>
    <div class="carousel-item">
      <a href="/products/?category=hive">
      <%= image_tag('hive.jpg', class: "d-block img-fluid") %>
      </a>
      <div class="carousel-caption d-none d-md-block">
        <h3>Hives</h3>
      </div>
    </div>
    <div class="carousel-item">
      <a href="/products/?category=bee">
      <%= image_tag('packages.jpg', class: "d-block img-fluid") %>
      </a>
      <div class="carousel-caption d-none d-md-block">
        <h3>Bee Packages</h3>
      </div>
    </div>
    <div class="carousel-item">
      <a href="/products/?category=equipment">
      <%= image_tag('equipment.jpeg', class: "d-block img-fluid") %>
      </a>
      <div class="carousel-caption d-none d-md-block">
        <h3>Equipment</h3>
      </div>
    </div>
    <div class="carousel-item">
      <a href="/products/?category=bee">
      <%= image_tag('beeswax.jpg', class: "d-block img-fluid") %>
      </a>
      <div class="carousel-caption d-none d-md-block">
        <h3>Bee Products</h3>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/products/index.html.erb
<div class="row">
  <% @products.each do |product| %>
      <div class='col-lg-4'>
        <%= link_to product_path(product) do  %>
        <%= render 'product', :product => product %>
        <% end %>
      </div>
  <% end %>
</div>

app/views/products/show.html.erb
<% if @order %>
  <%= render "layouts/errors", :object => @order %>
<% end %>



<%= image_tag(@product.photo.url(:large)) %>
<p><%= @product.name %> | <%= number_to_currency @product.price %></p>

<%= render "products/form" %>
<% if @reviews.any? %>
  <p class="white">Recent Reviews: </p>
  <% @reviews.each do |review| %>

  <div class='card mt-3'>
    <div class='card-body'>
      <p><%=review.content_body %></p>
      <p> - <%= review.user.email %></p>
      <p> - <%= review.rating %></p>
    </div>
  </div>
  <%end%>
  <%= link_to 'Add a review', new_product_review_path(@product) %>
<%else%>
    <%= link_to 'Add a review', new_product_review_path(@product) %>
<%end%>