config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:registrations => "user/registrations"}
  resources :products do
    resources :reviews
  end
  resource :home, :index

  resources :charges, :only => [:new, :create]

  resources :order_items

  resources :addresses, :only => [:create]

  resource :cart, only: [:show]

  root :to => "products#home"

  get "cart/selectaddress", to: "carts#selectaddress"
  post "cart/processaddress", to: "carts#processaddress"


  get "*path", to: redirect('/')
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <h3>Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-warning mb-3">
  <a class="navbar-brand ml-2" href="/">Bob's Bees</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item ml-1 mr-1">
          <%= link_to "All Products", products_path,:class => "nav-link text-dark link-text" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item ml-1 mr-1">
            <%= link_to "Upload Photos", new_user_registration_path, :class => "nav-link text-dark link-text" %>
          </li>
        <% end %>
      </ul>
    </ul>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item ml-1 mr-1">
        <%= link_to image_tag('cart.png', class: "icon"), cart_path  %>
        <span id="items-in-cart"><%= items_in_cart %></span>
      </li>
      <li class="nav-item ml-1 mr-1">
        <% if user_signed_in? %>
          <%= link_to "Logout, #{current_user.email}", destroy_user_session_path, method: :delete, :class => "nav-link text-dark link-text"%>
        <% else %>
          <%= link_to "Login", new_user_session_path, :class => "btn btn-dark text-white nav-link link-text"%>
      </li>
      <li class="nav-item ml-1">
          <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-dark text-white nav-link link-text" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <% flash.each do |key, value| %>
      <% case key %>
      <% when "notice" %>
        <% type = 'success' %>
      <% when "alert" %>
        <% type = 'danger' %>
      <% else %>
        <% type = 'primary' %>
      <% end %>
      <div class="alert alert-<%= type %>">
        <%= value %>
      </div>
    <% end %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>